# Uncomment the next line to define a global platform for your project

platform :ios, '8.0'

target 'Weibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weibo

pod 'Alamofire', '4.7.3'
pod 'SnapKit', '4.2.0'
pod 'YYModel', '1.0.4'
pod 'SVProgressHUD', '2.2.5'
pod 'Kingfisher', '4.10.1'
pod 'pop', '1.0.12'
pod 'FMDB', '2.7.5'
pod 'SDWebImage', '4.4.2'
pod 'SKPhotoBrowser', '6.0.0'

end
